import localFont from "next/font/local";
import "./globals.css";
import { Cabin } from "next/font/google";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const cabin = Cabin({
  weight: '600',
  subsets:['latin'],
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${cabin.className} antialiased`}>
        <div className="main-body md:w-3/5 m-0.5 md:m-auto p-3">
          {children}
        </div>
      </body>
    </html>
  );
}
